In [1]:
import torch
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
import sys
sys.path.append("..")
from BrainTumorDataset import BrainTumorDataset

In [2]:
dataset = BrainTumorDataset("../dataset/images/", "../dataset/masks/")
data_loader = DataLoader(dataset, batch_size = 64, shuffle = False, num_workers = 0)

In [3]:
image_channels_sum = 0
mask_channels_sum = 0
image_channels_squared_sum = 0
mask_channels_squared_sum = 0
num_batches = 0 

In [4]:
for image, mask in data_loader:
    image_channels_sum += torch.mean(image, dim = [0,2,3])
    mask_channels_sum += torch.mean(mask, dim = [0,2,3])
    image_channels_squared_sum += torch.mean(image**2, dim = [0,2,3])
    mask_channels_squared_sum += torch.mean(mask**2, dim = [0,2,3])
    num_batches += 1
    
image_mean = image_channels_sum / num_batches
mask_mean = mask_channels_sum / num_batches
image_std =(image_channels_squared_sum / num_batches - image_mean**2) ** 0.5
mask_std =(mask_channels_squared_sum / num_batches - mask_mean**2) ** 0.5

In [5]:
image_mean

tensor([0.0913, 0.0828, 0.0869])

In [6]:
image_std

tensor([0.1349, 0.1234, 0.1288])

In [7]:
mask_mean

tensor([0.0102])

In [8]:
mask_std

tensor([0.1005])